# Generated by Django 5.0.9 on 2024-10-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
